#!/usr/bin/expect
set timeout -1

set status [catch {exec zenity --password "--text=Bitte geben Sie Ihr aktuelles Passwort ein"} oldpasswd]
if {$status != 0} exit
spawn passwd
expect "Current password:"
send -- "$oldpasswd\r"
expect {
    "passwd: Passwort nicht geändert" {exit}
    "Geben Sie ein neues Passwort ein:" {
        set status [catch {exec zenity --password "--text=Bitte geben Sie Ihr neues Passwort ein"} newpasswd1]
        if {$status != 0} exit
        send -- "$newpasswd1\r"
    }
}

set status [catch {exec zenity --password "--text=Bitte geben Sie Ihr neues Passwort erneut ein"} newpasswd2]
if {$status != 0} exit
expect "Geben Sie das neue Passwort erneut ein:"
send -- "$newpasswd2\r"

expect eof



